## ดึงข้อมูลจากทุก Folder มาต่อกัน โดยเลือกเฉพาะ File: transcript_backbiter.csv เท่านั้น

In [82]:
import pandas as pd
import glob
import os

root_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/CANDOR Corpus - Conversations (no video)'

# ส่วนที่ 1: รวมไฟล์ transcript_backbiter.csv
search_pattern_1 = os.path.join(root_path, '**', 'transcript_backbiter.csv')
file_paths_1 = glob.glob(search_pattern_1, recursive=True)
all_transcripts = []

for file in file_paths_1:
    try:
        df = pd.read_csv(file)
        conv_id = os.path.basename(os.path.dirname(os.path.dirname(file)))
        df['conversation_id'] = conv_id
        all_transcripts.append(df)
    except Exception as e:
        print(f"อ่านไฟล์ transcript {file} ไม่สำเร็จ: {e}")

if all_transcripts:
    combined_transcript = pd.concat(all_transcripts, ignore_index=True)
    output_path_1 = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_backbiter.csv'
    combined_transcript.to_csv(output_path_1, index=False, encoding='utf-8-sig')
    print(f"บันทึก Transcript เรียบร้อย: {output_path_1}")

# ส่วนที่ 2: รวมไฟล์ survey.csv
search_pattern_2 = os.path.join(root_path, '**', 'survey.csv')
file_paths_2 = glob.glob(search_pattern_2, recursive=True)
all_surveys = []

for file in file_paths_2:
    try:
        df = pd.read_csv(file)
        all_surveys.append(df)
    except Exception as e:
        print(f"อ่านไฟล์ survey {file} ไม่สำเร็จ: {e}")

if all_surveys:
    combined_survey = pd.concat(all_surveys, ignore_index=True)
    output_path_2 = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey.csv'
    combined_survey.to_csv(output_path_2, index=False, encoding='utf-8-sig')
    print(f"บันทึก Survey เรียบร้อย: {output_path_2}")

บันทึก Transcript เรียบร้อย: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_backbiter.csv
บันทึก Survey เรียบร้อย: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey.csv

In [83]:
from IPython.display import display
print(" ตัวอย่างข้อมูล combined_transcript_backbiter.csv ")
display(pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_backbiter.csv").head(6))
print("\n ตัวอย่างข้อมูล combined_survey.csv ")
display(pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey.csv").head(6))

 ตัวอย่างข้อมูล combined_transcript_backbiter.csv

,turn_id,speaker,start,stop,utterance,backchannel,backchannel_count,backchannel_speaker,backchannel_start,backchannel_stop,interval,delta,questions,end_question,overlap,n_words,conversation_id
0,0,5f2f6bd965964e35e20c7445,1.01,58.26,fine. Perfect. Yeah. Mhm. Mhm. Yeah. Yeah.,NaN,0,NaN,NaN,NaN,NaN,57.25,0,False,False,7,3a51d3fd-a343-4177-b48e-a694a14c5891
1,1,5c8be0dd542fbd0016924f5f,78.44,79.25,"No,",NaN,0,NaN,NaN,NaN,20.18,0.81,0,False,False,1,3a51d3fd-a343-4177-b48e-a694a14c5891
2,2,5f2f6bd965964e35e20c7445,78.94,81.56,"No. Hi, how are you?",NaN,0,NaN,NaN,NaN,-0.31,2.62,1,True,True,5,3a51d3fd-a343-4177-b48e-a694a14c5891
3,3,5c8be0dd542fbd0016924f5f,82.14,83.36,I'm good. How are you?,NaN,0,NaN,NaN,NaN,0.58,1.22,1,True,False,6,3a51d3fd-a343-4177-b48e-a694a14c5891
4,4,5f2f6bd965964e35e20c7445,83.94,85.26,Good thanks.,NaN,0,NaN,NaN,NaN,0.58,1.32,0,False,False,2,3a51d3fd-a343-4177-b48e-a694a14c5891
5,5,5c8be0dd542fbd0016924f5f,85.44,89.68,Hm My name is played to,Mhm.,1,5f2f6bd965964e35e20c7445,87.74,88.76,0.18,4.24,0,False,False,6,3a51d3fd-a343-4177-b48e-a694a14c5891

 ตัวอย่างข้อมูล combined_survey.csv

,user_id,partner_id,convo_id,date,survey_duration_in_seconds,time_zone,pre_affect,pre_arousal,technical_quality,conv_length,...,my_conscientious,my_neurotic,my_open,your_extraversion,your_agreeable,your_conscientious,your_neurotic,your_open,who_i_talked_to_most_past24,most_common_format_past24
0,5c8be0dd542fbd0016924f5f,5f2f6bd965964e35e20c7445,3a51d3fd-a343-4177-b48e-a694a14c5891,2020-10-10,3450,6.0,6.0,7.0,1.0,30.0,...,5.000000,1.000000,2.666667,3.666667,4.333333,4.000000,2.000000,3.333333,NaN,NaN
1,5f2f6bd965964e35e20c7445,5c8be0dd542fbd0016924f5f,3a51d3fd-a343-4177-b48e-a694a14c5891,2020-10-10,4993,6.0,8.0,8.0,1.0,28.0,...,4.666667,3.666667,5.000000,3.000000,4.333333,4.000000,3.000000,3.000000,NaN,NaN
2,55a43cf3fdf99b02ff6cb0b4,5f220462c16ecb68c97ccad9,0c6b3a4a-7832-44ea-8830-ff727f2b803c,2020-11-16,2477,7.0,4.0,5.0,1.0,27.0,...,4.000000,2.666667,4.000000,4.000000,4.000000,4.000000,2.333333,3.333333,NaN,NaN
3,5f220462c16ecb68c97ccad9,55a43cf3fdf99b02ff6cb0b4,0c6b3a4a-7832-44ea-8830-ff727f2b803c,2020-11-16,4058,6.0,7.0,6.0,1.0,25.0,...,2.666667,3.333333,3.333333,3.000000,3.000000,3.000000,3.000000,3.000000,NaN,NaN
4,5c6f2e7632cb70000169b490,5f1b1822f97ccd2b3e486960,0bfaca02-9d10-4880-8065-749c1f8891cf,2020-11-16,5166,5.0,7.0,6.0,2.0,26.0,...,5.000000,1.000000,3.666667,4.000000,5.000000,5.000000,1.000000,4.333333,NaN,NaN
5,5f1b1822f97ccd2b3e486960,5c6f2e7632cb70000169b490,0bfaca02-9d10-4880-8065-749c1f8891cf,2020-11-16,3132,6.0,8.0,5.0,2.0,27.0,...,5.000000,2.333333,4.000000,4.000000,4.000000,3.666667,2.666667,3.666667,NaN,NaN

## Selection specifically columns: user_id, partner_id, convo_id, age, conv_leader from combined_survey.csv only

In [84]:
combined_survey_final = combined_survey[['user_id', 'partner_id', 'convo_id', 'age', 'conv_leader']]
output_path_3 = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey_final.csv'
combined_survey_final.to_csv(output_path_3, index=False, encoding='utf-8-sig')
print(f"บันทึก combined_survey_final เรียบร้อย: {output_path_3}")

บันทึก combined_survey_final เรียบร้อย: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey_final.csv

In [85]:
print(" ตัวอย่างข้อมูล combined_survey_final.csv")
pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey_final.csv").head(6)

 ตัวอย่างข้อมูล combined_survey_final.csv

,user_id,partner_id,convo_id,age,conv_leader
0,5c8be0dd542fbd0016924f5f,5f2f6bd965964e35e20c7445,3a51d3fd-a343-4177-b48e-a694a14c5891,29.0,7.0
1,5f2f6bd965964e35e20c7445,5c8be0dd542fbd0016924f5f,3a51d3fd-a343-4177-b48e-a694a14c5891,52.0,3.0
2,55a43cf3fdf99b02ff6cb0b4,5f220462c16ecb68c97ccad9,0c6b3a4a-7832-44ea-8830-ff727f2b803c,44.0,7.0
3,5f220462c16ecb68c97ccad9,55a43cf3fdf99b02ff6cb0b4,0c6b3a4a-7832-44ea-8830-ff727f2b803c,44.0,9.0
4,5c6f2e7632cb70000169b490,5f1b1822f97ccd2b3e486960,0bfaca02-9d10-4880-8065-749c1f8891cf,47.0,5.0
5,5f1b1822f97ccd2b3e486960,5c6f2e7632cb70000169b490,0bfaca02-9d10-4880-8065-749c1f8891cf,26.0,5.0

## Selection specifically columns: n_words, questions, speaker, delta, conversation_id from combined_transcript.csv only

In [86]:
combined_transcript_final = combined_transcript[['n_words', 'questions', 'speaker', 'delta', 'conversation_id']]
output_path_4 = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final.csv'
combined_transcript_final.to_csv(output_path_4, index=False, encoding='utf-8-sig')
print(f"บันทึก combined_transcript_final เรียบร้อย: {output_path_4}")

บันทึก combined_transcript_final เรียบร้อย: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final.csv

In [87]:
print(" ตัวอย่างข้อมูล combined_transcript_final.csv")
pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final.csv").head(6)

 ตัวอย่างข้อมูล combined_transcript_final.csv

,n_words,questions,speaker,delta,conversation_id
0,7,0,5f2f6bd965964e35e20c7445,57.25,3a51d3fd-a343-4177-b48e-a694a14c5891
1,1,0,5c8be0dd542fbd0016924f5f,0.81,3a51d3fd-a343-4177-b48e-a694a14c5891
2,5,1,5f2f6bd965964e35e20c7445,2.62,3a51d3fd-a343-4177-b48e-a694a14c5891
3,6,1,5c8be0dd542fbd0016924f5f,1.22,3a51d3fd-a343-4177-b48e-a694a14c5891
4,2,0,5f2f6bd965964e35e20c7445,1.32,3a51d3fd-a343-4177-b48e-a694a14c5891
5,6,0,5c8be0dd542fbd0016924f5f,4.24,3a51d3fd-a343-4177-b48e-a694a14c5891

In [88]:
import pandas as pd

# 1. โหลดข้อมูล
transcript_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final.csv'
survey_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_survey_final.csv'

transcript = pd.read_csv(transcript_path)
survey = pd.read_csv(survey_path)

print(f"โหลดข้อมูลเรียบร้อย")

# Step 1: Aggregrate columns: questions, n_words, delta group by conversation_id and speaker
speaker_level = transcript.groupby(['conversation_id', 'speaker'])[['questions', 'n_words', 'delta']].sum().reset_index()
# rename columns
speaker_level.rename(columns={
    'questions': 'total_questions',
    'n_words': 'total_words',
    'delta': 'total_speaking_time'
}, inplace=True)

# Step 2: ดึงข้อมูลจาก Survey
# 2.1 ดึงอายุ (Age) -> ดูจากแถวตัวเอง (user_id = speaker)
survey_age = survey[['convo_id', 'user_id', 'age']]
merged_df = pd.merge(speaker_level, survey_age, 
                     left_on=['conversation_id', 'speaker'], 
                     right_on=['convo_id', 'user_id'], 
                     how='inner')

# 2.2 ดึงคะแนนผู้นำ (Conv Leader) -> ดูจากแถวที่คนอื่นให้เรา (partner_id = speaker)
survey_score = survey[['convo_id', 'partner_id', 'conv_leader']]
merged_df = pd.merge(merged_df, survey_score,
                     left_on=['conversation_id', 'speaker'], 
                     right_on=['convo_id', 'partner_id'], 
                     how='inner')

# (ตอนนี้ merged_df จะมีคะแนน conv_leader ที่ "ได้รับ" จากคู่สนทนาแล้ว)

# Step 3: คำนวณ Age Diff (เหมือนเดิม)
merged_df['age_diff'] = merged_df.groupby('conversation_id')['age'].transform(lambda x: x.max() - x.min())

# Step 4: ตัดสิน Question Leader (Elder vs Younger)
leader_map = {}

for conv_id, group in merged_df.groupby('conversation_id'):
    if len(group) == 2:
        group = group.sort_values('age')
        younger = group.iloc[0]
        older = group.iloc[1]
        
        winner = 'Tie'
        
        if older['age'] > younger['age']:
            if older['total_questions'] > younger['total_questions']:
                winner = 'Elder'
            elif younger['total_questions'] > older['total_questions']:
                winner = 'Younger'
        else:
            winner = 'Same Age'
            
        leader_map[conv_id] = winner

merged_df['question_leader'] = merged_df['conversation_id'].map(leader_map)

# Step 5: จัดระเบียบและบันทึก
# ลบคอลัมน์ ID ที่ใช้ merge แล้วไม่จำเป็นต้องโชว์
cols_to_keep = ['conversation_id', 'speaker', 'age', 'conv_leader', 'age_diff', 
                'total_questions', 'total_words', 'total_speaking_time', 'question_leader']

final_df = merged_df[cols_to_keep]

# บันทึกไฟล์
output_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_speaker_summary_corrected.csv'
final_df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"\n✅ แก้ไขเรียบร้อย! (คะแนน conv_leader คือคะแนนที่ได้รับจาก Partner)")
print(f"ไฟล์ใหม่อยู่ที่: {output_path}")

โหลดข้อมูลเรียบร้อย

✅ แก้ไขเรียบร้อย! (คะแนน conv_leader คือคะแนนที่ได้รับจาก Partner)
ไฟล์ใหม่อยู่ที่: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_speaker_summary_corrected.csv

In [89]:
print(" ตัวอย่างข้อมูล combined_transcript_speaker_summary_corrected.csv")
pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_speaker_summary_corrected.csv").head(6)

 ตัวอย่างข้อมูล combined_transcript_speaker_summary_corrected.csv

,conversation_id,speaker,age,conv_leader,age_diff,total_questions,total_words,total_speaking_time,question_leader
0,0020a0c5-1658-4747-99c1-2839e736b481,5a73899f9cdd1800017786f0,34.0,3.0,2.0,14,2297,715.71,Younger
1,0020a0c5-1658-4747-99c1-2839e736b481,5fa072f4f4aa580b63834357,32.0,7.0,2.0,43,5402,2049.09,Younger
2,002d68da-7738-4177-89d9-d72ae803e0e4,5f482b0da1cde52de45f174c,19.0,7.0,5.0,22,3488,1211.43,Elder
3,002d68da-7738-4177-89d9-d72ae803e0e4,5f57120cba207c18f058a62b,24.0,5.0,5.0,30,3622,1011.01,Elder
4,00411458-8275-4b92-a000-d52187f03604,5d510396f6725b001a4fc025,22.0,1.0,8.0,27,1544,459.12,Younger
5,00411458-8275-4b92-a000-d52187f03604,5dd5bc3bd5cef8000b9861d5,30.0,8.0,8.0,26,5828,1812.35,Younger

In [90]:
import pandas as pd

# 1. โหลดข้อมูลไฟล์ล่าสุด (ที่แก้ Logic คะแนน Leader แล้ว)
input_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_speaker_summary_corrected.csv'
df = pd.read_csv(input_path)

print(f" โหลดข้อมูลเรียบร้อย: {len(df)} แถว")

# 2. สร้าง Dictionary เพื่อเก็บผลลัพธ์ว่าใครเป็น Actual Leader ในแต่ละคู่
actual_leader_map = {}

print(" กำลังประมวลผลหา Actual Leader (จากคะแนน Vote)...")

for conv_id, group in df.groupby('conversation_id'):
    if len(group) == 2:
        # เรียงตามอายุ (น้อย -> มาก) เพื่อระบุตัวตน
        group = group.sort_values('age')
        
        younger = group.iloc[0]
        older = group.iloc[1]
        
        winner = 'Tie' # ค่าเริ่มต้น (เสมอ)
        
        # เช็คว่าอายุต่างกันจริงไหม
        if older['age'] > younger['age']:
            # เทียบ "คะแนนความเป็นผู้นำ" (conv_leader)
            if older['conv_leader'] > younger['conv_leader']:
                winner = 'Elder'
            elif younger['conv_leader'] > older['conv_leader']:
                winner = 'Younger'
            else:
                winner = 'Tie' # คะแนนเท่ากัน
        else:
            winner = 'Same Age' # อายุเท่ากัน
            
        actual_leader_map[conv_id] = winner

# 3. ใส่ผลลัพธ์กลับเข้าไปใน DataFrame
# (คอลัมน์ใหม่: actual_leader)
df['actual_leader'] = df['conversation_id'].map(actual_leader_map)

# 4. บันทึกไฟล์ใหม่
output_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete.csv'
df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"\n✅ เสร็จสมบูรณ์!")
print(f"📂 บันทึกที่: {output_path}")
print("-" * 30)

# แสดงตัวอย่างข้อมูล
cols_to_show = ['conversation_id', 'age', 'conv_leader', 'question_leader', 'actual_leader']
print(df[cols_to_show].head(6))

print("-" * 30)
print("📊 สรุปผล Actual Leader (ใครได้คะแนนผู้นำเยอะกว่า?):")
print(df['actual_leader'].value_counts())

 โหลดข้อมูลเรียบร้อย: 3312 แถว
 กำลังประมวลผลหา Actual Leader (จากคะแนน Vote)...

✅ เสร็จสมบูรณ์!
📂 บันทึกที่: /Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete.csv
------------------------------
                        conversation_id   age  conv_leader question_leader  \
0  0020a0c5-1658-4747-99c1-2839e736b481  34.0          3.0         Younger
1  0020a0c5-1658-4747-99c1-2839e736b481  32.0          7.0         Younger
2  002d68da-7738-4177-89d9-d72ae803e0e4  19.0          7.0           Elder
3  002d68da-7738-4177-89d9-d72ae803e0e4  24.0          5.0           Elder
4  00411458-8275-4b92-a000-d52187f03604  22.0          1.0         Younger
5  00411458-8275-4b92-a000-d52187f03604  30.0          8.0         Younger

  actual_leader
0       Younger
1       Younger
2       Younger
3       Younger
4         Elder
5         Elder
------------------------------
📊 สรุปผล Actual Leader (ใครได้คะแนนผู้นำเยอะกว่า?):
actual_leader
Elder       1742
Younger      982
Tie          408
Same Age     180
Name: count, dtype: int64

In [91]:
print(" ตัวอย่างข้อมูล combined_transcript_final_complete.csv")
pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete.csv").head(6)

 ตัวอย่างข้อมูล combined_transcript_final_complete.csv

,conversation_id,speaker,age,conv_leader,age_diff,total_questions,total_words,total_speaking_time,question_leader,actual_leader
0,0020a0c5-1658-4747-99c1-2839e736b481,5a73899f9cdd1800017786f0,34.0,3.0,2.0,14,2297,715.71,Younger,Younger
1,0020a0c5-1658-4747-99c1-2839e736b481,5fa072f4f4aa580b63834357,32.0,7.0,2.0,43,5402,2049.09,Younger,Younger
2,002d68da-7738-4177-89d9-d72ae803e0e4,5f482b0da1cde52de45f174c,19.0,7.0,5.0,22,3488,1211.43,Elder,Younger
3,002d68da-7738-4177-89d9-d72ae803e0e4,5f57120cba207c18f058a62b,24.0,5.0,5.0,30,3622,1011.01,Elder,Younger
4,00411458-8275-4b92-a000-d52187f03604,5d510396f6725b001a4fc025,22.0,1.0,8.0,27,1544,459.12,Younger,Elder
5,00411458-8275-4b92-a000-d52187f03604,5dd5bc3bd5cef8000b9861d5,30.0,8.0,8.0,26,5828,1812.35,Younger,Elder

In [99]:
# check missing value
final_df = pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete.csv")
print(final_df.shape)
print(final_df.isnull().sum())

(3312, 10)
conversation_id         0
speaker                 0
age                    56
conv_leader            55
age_diff                4
total_questions         0
total_words             0
total_speaking_time     0
question_leader         0
actual_leader           0
dtype: int64

In [100]:
# 1. หา List ของ conversation_id ที่มีค่าว่าง (แม้แต่จุดเดียวในแถวใดแถวหนึ่ง)
ids_with_missing = final_df[final_df.isnull().any(axis=1)]['conversation_id'].unique()

# 2. กรองเอาเฉพาะแถวที่ conversation_id ไม่อยู่ใน List ของพวกที่มีปัญหา
final_df_cleaned = final_df[~final_df['conversation_id'].isin(ids_with_missing)]

In [101]:
# check missing value again
print(final_df_cleaned.shape)
print(final_df_cleaned.isnull().sum())
print("---- Done!!! Do not have missing value ---")

# บันทึกไฟล์ใหม่
output_path = '/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete_cleaned.csv'
final_df_cleaned.to_csv(output_path, index=False, encoding='utf-8-sig')
print("\nDone! บันทึกไฟล์สำเร็จ")

(3204, 10)
conversation_id        0
speaker                0
age                    0
conv_leader            0
age_diff               0
total_questions        0
total_words            0
total_speaking_time    0
question_leader        0
actual_leader          0
dtype: int64
---- Done!!! Do not have missing value ---

Done! บันทึกไฟล์สำเร็จ

In [102]:
# Check file ที่สมบูรณ์ กำจัด missing value
pd.read_csv("/Users/kunanon/Desktop/STATxCUYear3/INFO VISUAL/Merge Data/combined_transcript_final_complete_cleaned.csv").head(6)

,conversation_id,speaker,age,conv_leader,age_diff,total_questions,total_words,total_speaking_time,question_leader,actual_leader
0,0020a0c5-1658-4747-99c1-2839e736b481,5a73899f9cdd1800017786f0,34.0,3.0,2.0,14,2297,715.71,Younger,Younger
1,0020a0c5-1658-4747-99c1-2839e736b481,5fa072f4f4aa580b63834357,32.0,7.0,2.0,43,5402,2049.09,Younger,Younger
2,002d68da-7738-4177-89d9-d72ae803e0e4,5f482b0da1cde52de45f174c,19.0,7.0,5.0,22,3488,1211.43,Elder,Younger
3,002d68da-7738-4177-89d9-d72ae803e0e4,5f57120cba207c18f058a62b,24.0,5.0,5.0,30,3622,1011.01,Elder,Younger
4,00411458-8275-4b92-a000-d52187f03604,5d510396f6725b001a4fc025,22.0,1.0,8.0,27,1544,459.12,Younger,Elder
5,00411458-8275-4b92-a000-d52187f03604,5dd5bc3bd5cef8000b9861d5,30.0,8.0,8.0,26,5828,1812.35,Younger,Elder